{
 "title": "Karpenter Capacity",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, nodepool)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, zone)"
    }
   },
   {
    "name": "arch",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, arch)"
    }
   },
   {
    "name": "capacity_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, capacity_type)"
    }
   },
   {
    "name": "instance_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, instance_type)"
    }
   },
   {
    "name": "distribution_filter",
    "query": "arch,capacity_type,instance_type,namespace,node,nodepool,zone"
   },
   { "name": "cluster_name", "label": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Nodes Created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(k8s_cluster_name) (karpenter_nodes_created{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "{{k8s_cluster_name}}"
    }
   ]
  },
  {
   "title": "Nodes Terminated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(k8s_cluster_name) (karpenter_nodes_terminated{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "{{k8s_cluster_name}}"
    }
   ]
  },
  {
   "title": "Pod Phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(phase)(karpenter_pods_state{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pod Distribution: $distribution_filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by ($distribution_filter)(\n    karpenter_pods_state{arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", nodepool=~\"$nodepool\", k8s_cluster_name=~\"$cluster_name\"}\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Nodepool Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "karpenter_nodepool_usage{resource_type=\"cpu\", k8s_cluster_name=~\"$cluster_name\"} / karpenter_nodepool_limit{resource_type=\"cpu\", k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "CPU Limit Utilization"
    },
    {
     "expr": "count by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"\",resource_type=\"cpu\", k8s_cluster_name=~\"$cluster_name\"}) # Selects a single resource type to get node count"
    },
    {
     "expr": "karpenter_nodepool_usage{resource_type=\"memory\", k8s_cluster_name=~\"$cluster_name\"} / karpenter_nodepool_limit{resource_type=\"memory\", k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Memory Limit Utilization"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"\",resource_type=\"cpu\", k8s_cluster_name=~\"$cluster_name\"})"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"\",resource_type=\"memory\", k8s_cluster_name=~\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count(karpenter_nodes_allocatable{arch=~\"$arch\",capacity_type=\"spot\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"}) or vector(0)) / count(karpenter_nodes_allocatable{arch=~\"$arch\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"cpu\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "((karpenter_nodes_total_daemon_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"} or karpenter_nodes_allocatable*0) + \n(karpenter_nodes_total_pod_requests{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"} or karpenter_nodes_allocatable*0)) / \nkarpenter_nodes_allocatable{resource_type=\"memory\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "karpenter_nodes_total_daemon_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"} + \nkarpenter_nodes_total_pod_requests{resource_type=\"pods\",arch=~\"$arch\",capacity_type=~\"$capacity_type\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\", k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "label_replace(\n    sum by (node)(node_time_seconds) - sum by (node)(node_boot_time_seconds),\n    \"node_name\", \"$1\", \"node\", \"(.+)\"\n)",
     "legendFormat": "Uptime"
    }
   ]
  }
 ]
}