{
 "title": "Kubernetes Cluster Autoscaler Stats",
 "description": "Super simple dashboard showing an overview of Kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to Prometheus",
 "tags": [ "prometheus" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{k8s_cluster_name=~\"$cluster_name\"})\n"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "gauge",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{k8s_cluster_name=~\"$cluster_name\",state=\"ready\"})/sum(cluster_autoscaler_nodes_count{k8s_cluster_name=~\"$cluster_name\"})*100"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{k8s_cluster_name=~\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "stat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{k8s_cluster_name=~\"$cluster_name\",activity=\"scaleDown\"})"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{k8s_cluster_name=~\"$cluster_name\",activity=\"autoscaling\"})"
    }
   ]
  },
  {
   "title": "Pod activity (evicted/unscheduled)",
   "type": "graph",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Number of Pods" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "graph",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{k8s_cluster_name=~\"$cluster_name\",state=\"ready\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{k8s_cluster_name=~\"$cluster_name\",state=\"unready\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{k8s_cluster_name=~\"$cluster_name\",state=\"notStarted\"})\n",
     "legendFormat": "not started"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Number of Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "scaled up total"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{k8s_cluster_name=~\"$cluster_name\"})",
     "legendFormat": "unneeded nodes"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{k8s_cluster_name=~\"$cluster_name\"})\n",
     "legendFormat": "total nodes"
    }
   ]
  },
  {
   "title": "Cluster direction?",
   "type": "stat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{k8s_cluster_name=~\"$cluster_name\"})-sum(cluster_autoscaler_scale_down_in_cooldown{k8s_cluster_name=~\"$cluster_name\"})"
    }
   ]
  }
 ]
}