{
 "title": "Logging metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit incoming events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_input_records_total{k8s_cluster_name=~\"$cluster_name\",name=~\"tail.*\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fluent-bit outgoing events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(fluentbit_output_proc_records_total{k8s_cluster_name=~\"$cluster_name\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logstash incoming events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_in_total{k8s_cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash outgoing events per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(logstash_node_pipeline_events_out_total{k8s_cluster_name=~\"$cluster_name\"}[1m])",
     "legendFormat": "{{pipeline}} pipe on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash events in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "logstash_node_queue_events{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{pipeline}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Logstash heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "logstash_node_mem_heap_max_bytes{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "Heap max on {{instance}}"
    },
    {
     "expr": "logstash_node_mem_heap_used_bytes",
     "legendFormat": "Heap used on {{instance}}"
    }
   ]
  },
  {
   "title": "FluentBit Input vs Output & Data Volume",
   "type": "timeseries",
   "description": "Tracks FluentBit’s end-to-end log processing — from records ingested to records delivered, along with the volume of outgoing log data.\n\nMismatch between record rate and byte rate – High records/sec with low KB/sec may indicate malformed or empty logs.\n\nFlat lines – FluentBit may be stalled, misconfigured, or not ingesting logs.\n\nSudden spikes or drops – Possible log bursts, restarts, or downstream issues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[5m]))",
     "legendFormat": "Input Records/sec"
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[5m]))",
     "legendFormat": "Output Records/sec"
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[5m])) / 1024",
     "legendFormat": "Output KB/sec"
    }
   ]
  },
  {
   "title": "FluentBit Output Issues (Errors, Drops, Retries)",
   "type": "timeseries",
   "description": "Detects issues in FluentBit output processing such as plugin errors, dropped records and retry storms.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total[5m]))",
     "legendFormat": "Retries/sec"
    },
    {
     "expr": "sum(rate(fluentbit_output_errors_total[5m]))",
     "legendFormat": "Errors/sec"
    },
    {
     "expr": "sum(rate(fluentbit_output_dropped_records_total[5m]))",
     "legendFormat": "Dropped Records/sec"
    }
   ]
  },
  {
   "title": "Fluent Bit Memory Usage (% of Limit)",
   "type": "timeseries",
   "description": "Shows Fluent Bit memory usage as a percentage of the container's memory limit, grouped by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sort_desc((sum(container_memory_working_set_bytes{container=\"fluent-bit\"}) by (container, pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", container=\"fluent-bit\"}) by (container, pod)) * 100)",
     "legendFormat": "{{pod}} - Memory %"
    }
   ]
  },
  {
   "title": "Fluent Bit CPU Usage (% of Limit)",
   "type": "timeseries",
   "description": "Shows Fluent Bit CPU usage as a percentage of the container's CPU limit, grouped by pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sort_desc((sum(rate(container_cpu_usage_seconds_total{container=\"fluent-bit\"}[5m])) by (container, pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\", container=\"fluent-bit\"}) by (container, pod)) * 100)",
     "legendFormat": "{{pod}} - CPU %"
    }
   ]
  },
  {
   "title": "FluentBit In-Memory Buffer Usage (MB)",
   "type": "timeseries",
   "description": "Displays the total size (in MB) of logs currently buffered in memory across all Fluent Bit input plugins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(fluentbit_input_storage_memory_bytes) / 1024 / 1024",
     "legendFormat": "In-Memory Buffer (MB)"
    }
   ]
  },
  {
   "title": "Fluent Bit Disk Buffer Usage (MB)",
   "type": "timeseries",
   "description": "Shows total size (in MB) of busy chunks written to disk by Fluent Bit input plugins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(fluentbit_input_storage_chunks_busy_bytes) / 1024 / 1024",
     "legendFormat": "Total Disk Buffer (MB)"
    }
   ]
  },
  {
   "title": "FluentBit Input Plugin Memory Overlimit",
   "type": "timeseries",
   "description": "Displays which Fluent Bit input plugins are currently over the memory buffer limit. A flatline means all are correctly under the memory limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(fluentbit_input_storage_overlimit) by (pod, name)",
     "legendFormat": "Overlimit: {{name}}"
    }
   ]
  },
  {
   "title": "Fluent Bit Chunk distribution: In-Memory, On-Disk, Total",
   "type": "timeseries",
   "description": "Tracks how Fluent Bit distributes log chunks between memory and disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_storage_fs_chunks_up) by (instance)",
     "legendFormat": "In-Memory Chunks - {{instance}}"
    },
    {
     "expr": "sum(fluentbit_storage_fs_chunks) by (instance)",
     "legendFormat": "Total Chunks (Memory + On-Disk) - {{instance}}"
    },
    {
     "expr": "sum(fluentbit_storage_fs_chunks_down) by (instance)",
     "legendFormat": "On-Disk Chunks - {{instance}}"
    }
   ]
  }
 ]
}