{
 "title": "Volume Autoscaler",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster_name", "query": { "query": "label_values(k8s_cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "PVCs available for scaling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(volume_autoscaler_num_valid_pvcs{k8s_cluster_name=~\"$cluster_name\"}) by (instance)",
     "legendFormat": "PVCs"
    },
    {
     "expr": "max(volume_autoscaler_num_pvcs_above_threshold{k8s_cluster_name=~\"$cluster_name\"}) by (instance)",
     "legendFormat": "PVCs need to be scaled"
    }
   ]
  },
  {
   "title": "Attempts vs Fails vs Failed volume autoscaler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "increase(volume_autoscaler_resize_attempted_total{k8s_cluster_name=~\"$cluster_name\"}[5m])",
     "legendFormat": "Attempted"
    },
    {
     "expr": "increase(volume_autoscaler_resize_failure_total{k8s_cluster_name=~\"$cluster_name\"}[5m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "increase(volume_autoscaler_resize_successful_total{k8s_cluster_name=~\"$cluster_name\"}[5m])",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Volume Autoscaler Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volume_autoscaler_release_info{k8s_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "{{app_kubernetes_io_version}}"
    }
   ]
  }
 ]
}